name: wps_wrf
channels:
  - conda-forge
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - babel=2.17.0
  - bcrypt=4.3.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cartopy=0.25.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - contourpy=1.3.2
  - cryptography=45.0.4
  - cycler=0.12.1
  - dataclasses=0.8
  - docutils=0.17.1
  - f90nml=1.4.4
  - folium=0.20.0
  - fonttools=4.58.4
  - freetype=2.13.3
  - freexl=2.0.0
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.1
  - giflib=5.2.2
  - h2=4.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - json-c=0.18
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - latexcodec=2.0.1
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.4
  - libarchive=3.8.1
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgdal-core=3.11.1
  - libgettextpo=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libhwy=1.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.49
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - minizip=4.0.10
  - munkres=1.1.4
  - muparser=2.3.5
  - ncurses=6.5
  - netcdf4=1.7.2
  - networkx=3.5
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.3.0
  - paramiko=3.5.1
  - pcre2=10.45
  - pillow=11.2.1
  - pip=25.1.1
  - proj=9.6.2
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pybtex=0.25.1
  - pybtex-docutils=1.0.3
  - pycparser=2.22
  - pygments=2.19.2
  - pynacl=1.5.0
  - pyogrio=0.11.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyshp=3.0.0
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.4
  - scikit-learn=1.7.1
  - scipy=1.16.1
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - snappy=1.2.2
  - snowballstemmer=3.0.1
  - sphinx=5.3.0
  - sphinx-design=0.3.0
  - sphinx-gallery=0.14.0
  - sphinx_rtd_theme=1.3.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-bibtex=2.6.1
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.50.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wheel=0.45.1
  - wrapt=1.17.2
  - wrf-python=1.4.0
  - xarray=2025.6.1
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - wget==3.2
prefix: /glade/work/krstulich/conda-envs/wps_wrf
